name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Create .nojekyll file
        run: |
          # Luodaan .nojekyll-tiedosto est채m채채n GitHub Pagesin Jekyll-k채sittely
          touch .nojekyll
          echo "Created .nojekyll file"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: false
          token: ${{ secrets.GITHUB_TOKEN }} 